openapi: 3.0.2
info:
  description: |
    Handles all identities for tracking the users of the Moov platform.
  title: Moov Identity API
  version: 0.0.1
servers:
- description: Local Testing
  url: https://local.moov.io/
- description: Production
  url: https://api.moov.io/
- description: Internal address of service
  url: https://identity.srvs.moov.local/
paths:
  /invites:
    get:
      operationId: ListInvites
      parameters:
      - description: Filter in only for specific Organization
        explode: true
        in: query
        name: orgID
        required: false
        schema:
          $ref: '#/components/schemas/UUID'
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Invite'
                maxItems: 300
                type: array
          description: Invites that are outstanding
        default:
          content:
            text/plain:
              schema:
                maxLength: 0
                pattern: //i
                type: string
          description: Empty response for unauthorized or any other returned http
            status code
      security:
      - GatewayAuth: []
      summary: List outstanding invites
      tags:
      - invites
    post:
      operationId: SendInvite
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendInvite'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invite'
          description: Invite sent
        default:
          content:
            text/plain:
              schema:
                maxLength: 0
                pattern: //i
                type: string
          description: Empty response for unauthorized or any other returned http
            status code
      security:
      - GatewayAuth: []
      summary: Send an email invite to a new user
      tags:
      - invites
  /invites/{inviteID}:
    delete:
      operationId: DisableInvite
      parameters:
      - description: ID of the invite to delete
        explode: false
        in: path
        name: inviteID
        required: true
        schema:
          $ref: '#/components/schemas/UUID'
        style: simple
      responses:
        "204":
          description: Invite was removed
        "404":
          content:
            text/plain:
              schema:
                maxLength: 0
                pattern: //i
                type: string
          description: Empty response for unauthorized or any other returned http
            status code
        default:
          content:
            text/plain:
              schema:
                maxLength: 0
                pattern: //i
                type: string
          description: Empty response for unauthorized or any other returned http
            status code
      security:
      - GatewayAuth: []
      summary: Delete an invite that was sent and invalidate the token.
      tags:
      - invites
  /authenticated:
    get:
      operationId: Authenticated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoggedIn'
          description: User successfully logged in.
        "404":
          content:
            text/plain:
              schema:
                maxLength: 0
                pattern: //i
                type: string
          description: Empty response for unauthorized or any other returned http
            status code
        default:
          content:
            text/plain:
              schema:
                maxLength: 0
                pattern: //i
                type: string
          description: Empty response for unauthorized or any other returned http
            status code
      security:
      - LoginAuth: []
      summary: |
        Complete a login via a OIDC.
        Once the OIDC client service has authenticated their identity the client service redirect to this endpoint.
      tags:
      - internal
  /register:
    post:
      operationId: RegisterWithCredentials
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
        description: Arguments needed register a user with OIDC credentials.
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoggedIn'
          description: User successfully registered, they can now log in
        default:
          content:
            text/plain:
              schema:
                maxLength: 0
                pattern: //i
                type: string
          description: Empty response for unauthorized or any other returned http
            status code
      security:
      - LoginAuth: []
      summary: "Called when the user is registering for the first time. It requires\
        \ that they have authenticated with a \nsupported OIDC provider and recieved\
        \ a valid invite code.\n"
      tags:
      - internal
  /identities:
    get:
      operationId: ListIdentities
      parameters:
      - description: Filter in only for specific Organization
        explode: true
        in: query
        name: orgID
        required: false
        schema:
          $ref: '#/components/schemas/UUID'
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Identity'
                maxItems: 300
                type: array
          description: List of identities/users in the system
        default:
          content:
            text/plain:
              schema:
                maxLength: 0
                pattern: //i
                type: string
          description: Empty response for unauthorized or any other returned http
            status code
      security:
      - GatewayAuth: []
      summary: List identities and associates userId
      tags:
      - identities
  /identities/{identityID}:
    delete:
      operationId: DisableIdentity
      parameters:
      - description: ID of the Identity to lookup
        explode: false
        in: path
        name: identityID
        required: true
        schema:
          $ref: '#/components/schemas/UUID'
        style: simple
      responses:
        "204":
          description: Invite was removed
        "404":
          content:
            text/plain:
              schema:
                maxLength: 0
                pattern: //i
                type: string
          description: Empty response for unauthorized or any other returned http
            status code
        default:
          content:
            text/plain:
              schema:
                maxLength: 0
                pattern: //i
                type: string
          description: Empty response for unauthorized or any other returned http
            status code
      security:
      - GatewayAuth: []
      summary: Disable an identity. Its left around for historical reporting
      tags:
      - identities
    get:
      operationId: GetIdentity
      parameters:
      - description: ID of the Identity to lookup
        explode: false
        in: path
        name: identityID
        required: true
        schema:
          $ref: '#/components/schemas/UUID'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Identity'
          description: List of identities/users in the system
        "404":
          content:
            text/plain:
              schema:
                maxLength: 0
                pattern: //i
                type: string
          description: Empty response for unauthorized or any other returned http
            status code
        default:
          content:
            text/plain:
              schema:
                maxLength: 0
                pattern: //i
                type: string
          description: Empty response for unauthorized or any other returned http
            status code
      security:
      - GatewayAuth: []
      summary: List identities and associates userId
      tags:
      - identities
    put:
      operationId: UpdateIdentity
      parameters:
      - description: ID of the Identity to lookup
        explode: false
        in: path
        name: identityID
        required: true
        schema:
          $ref: '#/components/schemas/UUID'
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateIdentity'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Identity'
          description: Identity was updated.
        "404":
          content:
            text/plain:
              schema:
                maxLength: 0
                pattern: //i
                type: string
          description: Empty response for unauthorized or any other returned http
            status code
        default:
          content:
            text/plain:
              schema:
                maxLength: 0
                pattern: //i
                type: string
          description: Empty response for unauthorized or any other returned http
            status code
      security:
      - GatewayAuth: []
      summary: Update a specific Identity
      tags:
      - identities
  /identities/{identityID}/credentials:
    get:
      operationId: ListCredentials
      parameters:
      - description: ID of the Identity to lookup
        explode: false
        in: path
        name: identityID
        required: true
        schema:
          $ref: '#/components/schemas/UUID'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Credential'
                maxItems: 300
                type: array
          description: List of credentials tied to this identity
        "404":
          content:
            text/plain:
              schema:
                maxLength: 0
                pattern: //i
                type: string
          description: Empty response for unauthorized or any other returned http
            status code
        default:
          content:
            text/plain:
              schema:
                maxLength: 0
                pattern: //i
                type: string
          description: Empty response for unauthorized or any other returned http
            status code
      security:
      - GatewayAuth: []
      summary: List the credentials this user has used.
      tags:
      - credentials
  /identities/{identityID}/credentials/{credentialID}:
    delete:
      operationId: DisableCredentials
      parameters:
      - description: ID of the Identity for the credential
        explode: false
        in: path
        name: identityID
        required: true
        schema:
          $ref: '#/components/schemas/UUID'
        style: simple
      - description: ID of the credential to disable
        explode: false
        in: path
        name: credentialID
        required: true
        schema:
          $ref: '#/components/schemas/UUID'
        style: simple
      responses:
        "204":
          description: Credential was disabled
        "404":
          content:
            text/plain:
              schema:
                maxLength: 0
                pattern: //i
                type: string
          description: Empty response for unauthorized or any other returned http
            status code
        default:
          content:
            text/plain:
              schema:
                maxLength: 0
                pattern: //i
                type: string
          description: Empty response for unauthorized or any other returned http
            status code
      security:
      - GatewayAuth: []
      summary: Disables a credential so it can't be used anymore to login
      tags:
      - credentials
components:
  responses:
    Empty:
      content:
        text/plain:
          schema:
            maxLength: 0
            pattern: //i
            type: string
      description: Empty response for unauthorized or any other returned http status
        code
  schemas:
    UUID:
      description: UUID v4
      format: uuid
      maxLength: 36
      pattern: ^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$
      type: string
    OptionalUUID:
      description: UUID v4
      format: uuid
      maxLength: 36
      nullable: true
      pattern: ^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$
      type: string
    Email:
      description: Email Address
      example: john.doe@gmail.com
      format: email
      maxLength: 255
      pattern: ^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$
      type: string
    DateTime:
      format: date-time
      maxLength: 24
      type: string
    OptionalDateTime:
      format: date-time
      maxLength: 24
      nullable: true
      type: string
    SubjectID:
      description: ID of the remote OIDC server gives to this identity
      example: aSDDfasd23Dfasdf
      maxLength: 255
      pattern: ^[0-9a-zA-Z_-]+$
      readOnly: true
      type: string
    Provider:
      description: OIDC provider that was used to handle authentication of this user.
      example: google
      maxLength: 255
      pattern: ^\w+$
      readOnly: true
      type: string
    SendInvite:
      additionalProperties: false
      description: Describes an invite that was sent to a user to join.
      example:
        email: john.doe@gmail.com
      properties:
        email:
          description: Email Address
          example: john.doe@gmail.com
          format: email
          maxLength: 255
          pattern: ^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$
          type: string
      type: object
    Invite:
      additionalProperties: false
      description: Describes an invite that was sent to a user to join.
      example:
        disabledBy: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        invitedBy: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        inviteID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        tenantID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        expiresOn: 2000-01-23T04:56:07.000+00:00
        disabledOn: 2000-01-23T04:56:07.000+00:00
        invitedOn: 2000-01-23T04:56:07.000+00:00
        redeemedOn: 2000-01-23T04:56:07.000+00:00
        email: john.doe@gmail.com
      properties:
        inviteID:
          description: UUID v4
          format: uuid
          maxLength: 36
          pattern: ^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$
          type: string
        tenantID:
          description: UUID v4
          format: uuid
          maxLength: 36
          pattern: ^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$
          type: string
        email:
          description: Email Address
          example: john.doe@gmail.com
          format: email
          maxLength: 255
          pattern: ^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$
          type: string
        invitedBy:
          description: UUID v4
          format: uuid
          maxLength: 36
          pattern: ^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$
          type: string
        invitedOn:
          format: date-time
          maxLength: 24
          type: string
        redeemedOn:
          format: date-time
          maxLength: 24
          nullable: true
          type: string
        expiresOn:
          format: date-time
          maxLength: 24
          type: string
        disabledOn:
          format: date-time
          maxLength: 24
          nullable: true
          type: string
        disabledBy:
          description: UUID v4
          format: uuid
          maxLength: 36
          nullable: true
          pattern: ^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$
          type: string
      type: object
    Identity:
      additionalProperties: false
      description: |
        Properties of an Identity. These users will under-go KYC checks thus all the information
      example:
        lastName: Doe
        lastLogin:
          credentialId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          "on": 2000-01-23T04:56:07.000+00:00
        addresses:
        - country: US
          validated: true
          address2: address2
          city: Cedar Falls
          identityID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          address1: 111 Main St.
          postalCode: "50613"
          state: IA
          type: primary
          addressID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - country: US
          validated: true
          address2: address2
          city: Cedar Falls
          identityID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          address1: 111 Main St.
          postalCode: "50613"
          state: IA
          type: primary
          addressID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - country: US
          validated: true
          address2: address2
          city: Cedar Falls
          identityID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          address1: 111 Main St.
          postalCode: "50613"
          state: IA
          type: primary
          addressID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - country: US
          validated: true
          address2: address2
          city: Cedar Falls
          identityID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          address1: 111 Main St.
          postalCode: "50613"
          state: IA
          type: primary
          addressID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - country: US
          validated: true
          address2: address2
          city: Cedar Falls
          identityID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          address1: 111 Main St.
          postalCode: "50613"
          state: IA
          type: primary
          addressID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        nickName: nickName
        inviteID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        phones:
        - number: number
          validated: true
          identityID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          phoneID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          type: home
        - number: number
          validated: true
          identityID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          phoneID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          type: home
        - number: number
          validated: true
          identityID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          phoneID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          type: home
        - number: number
          validated: true
          identityID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          phoneID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          type: home
        - number: number
          validated: true
          identityID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          phoneID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          type: home
        suffix: suffix
        birthDate: 2000-01-23T04:56:07.000+00:00
        firstName: John
        emailVerified: true
        disabledBy: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        identityID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        tenantID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        lastUpdatedOn: 2000-01-23T04:56:07.000+00:00
        middleName: Jimmy
        disabledOn: 2000-01-23T04:56:07.000+00:00
        registeredOn: 2000-01-23T04:56:07.000+00:00
        email: john.doe@gmail.com
        status: rejected
      properties:
        identityID:
          description: UUID v4
          format: uuid
          maxLength: 36
          pattern: ^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$
          type: string
        tenantID:
          description: UUID v4
          format: uuid
          maxLength: 36
          pattern: ^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$
          type: string
        firstName:
          example: John
          maxLength: 255
          pattern: ^\w+$
          type: string
        middleName:
          example: Jimmy
          maxLength: 255
          pattern: ^\w+$
          type: string
        lastName:
          example: Doe
          maxLength: 255
          pattern: ^\w+$
          type: string
        nickName:
          maxLength: 255
          nullable: true
          pattern: ^\w+$
          type: string
        suffix:
          maxLength: 255
          nullable: true
          pattern: ^\w+$
          type: string
        birthDate:
          format: date-time
          maxLength: 24
          type: string
        status:
          enum:
          - rejected
          - none
          - review-required
          - kyc
          - ofac
          - cip
          type: string
        email:
          description: Email Address
          example: john.doe@gmail.com
          format: email
          maxLength: 255
          pattern: ^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$
          type: string
        emailVerified:
          description: The user has verified they have access to this email
          readOnly: true
          type: boolean
        phones:
          items:
            $ref: '#/components/schemas/Phone'
          maxItems: 300
          type: array
        addresses:
          items:
            $ref: '#/components/schemas/Address'
          maxItems: 300
          type: array
        registeredOn:
          format: date-time
          maxLength: 24
          type: string
        lastLogin:
          $ref: '#/components/schemas/LastLogin'
        disabledOn:
          format: date-time
          maxLength: 24
          nullable: true
          type: string
        disabledBy:
          description: UUID v4
          format: uuid
          maxLength: 36
          nullable: true
          pattern: ^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$
          type: string
        lastUpdatedOn:
          format: date-time
          maxLength: 24
          type: string
        inviteID:
          description: UUID v4
          format: uuid
          maxLength: 36
          pattern: ^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$
          type: string
      required:
      - email
      - firstName
      - lastName
      type: object
    UpdateIdentity:
      additionalProperties: false
      description: |
        Properties of an Identity. These users will under-go KYC checks thus all the information
      example:
        firstName: John
        lastName: Doe
        addresses:
        - country: US
          validated: true
          address2: address2
          city: Cedar Falls
          address1: 111 Main St.
          postalCode: "50613"
          state: IA
          type: primary
          addressID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - country: US
          validated: true
          address2: address2
          city: Cedar Falls
          address1: 111 Main St.
          postalCode: "50613"
          state: IA
          type: primary
          addressID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - country: US
          validated: true
          address2: address2
          city: Cedar Falls
          address1: 111 Main St.
          postalCode: "50613"
          state: IA
          type: primary
          addressID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - country: US
          validated: true
          address2: address2
          city: Cedar Falls
          address1: 111 Main St.
          postalCode: "50613"
          state: IA
          type: primary
          addressID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - country: US
          validated: true
          address2: address2
          city: Cedar Falls
          address1: 111 Main St.
          postalCode: "50613"
          state: IA
          type: primary
          addressID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        nickName: nickName
        phones:
        - number: number
          validated: true
          phoneID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          type: home
        - number: number
          validated: true
          phoneID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          type: home
        - number: number
          validated: true
          phoneID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          type: home
        - number: number
          validated: true
          phoneID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          type: home
        - number: number
          validated: true
          phoneID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          type: home
        middleName: Jimmy
        suffix: suffix
        birthDate: 2000-01-23T04:56:07.000+00:00
        status: rejected
      properties:
        firstName:
          example: John
          maxLength: 255
          pattern: ^\w+$
          type: string
        middleName:
          example: Jimmy
          maxLength: 255
          pattern: ^\w+$
          type: string
        lastName:
          example: Doe
          maxLength: 255
          pattern: ^\w+$
          type: string
        nickName:
          maxLength: 255
          nullable: true
          pattern: ^\w+$
          type: string
        suffix:
          maxLength: 255
          nullable: true
          pattern: ^\w+$
          type: string
        birthDate:
          format: date-time
          maxLength: 24
          type: string
        status:
          enum:
          - rejected
          - none
          - review-required
          - kyc
          - ofac
          - cip
          type: string
        phones:
          items:
            $ref: '#/components/schemas/UpdatePhone'
          maxItems: 300
          type: array
        addresses:
          items:
            $ref: '#/components/schemas/UpdateAddress'
          maxItems: 300
          type: array
      required:
      - firstName
      - lastName
      type: object
    UpdatePhone:
      additionalProperties: false
      description: Phone number
      example:
        number: number
        validated: true
        phoneID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        type: home
      properties:
        phoneID:
          description: UUID v4
          format: uuid
          maxLength: 36
          pattern: ^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$
          type: string
        number:
          format: phone
          maxLength: 15
          pattern: ^[0-9]+$
          type: string
        validated:
          type: boolean
        type:
          enum:
          - home
          - mobile
          - work
          type: string
      type: object
    UpdateAddress:
      additionalProperties: false
      description: Address of the Identity
      example:
        country: US
        validated: true
        address2: address2
        city: Cedar Falls
        address1: 111 Main St.
        postalCode: "50613"
        state: IA
        type: primary
        addressID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        addressID:
          description: UUID v4
          format: uuid
          maxLength: 36
          pattern: ^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$
          type: string
        type:
          enum:
          - primary
          - secondary
          type: string
        address1:
          example: 111 Main St.
          maxLength: 255
          pattern: ^\w+$
          type: string
        address2:
          maxLength: 255
          nullable: true
          pattern: ^\w*$
          type: string
        city:
          example: Cedar Falls
          maxLength: 255
          pattern: ^\w+$
          type: string
        postalCode:
          example: "50613"
          maxLength: 5
          minLength: 5
          pattern: ^\d+$
          type: string
        state:
          example: IA
          maxLength: 2
          minLength: 2
          pattern: ^\w+$
          type: string
        country:
          example: US
          maxLength: 2
          minLength: 2
          pattern: ^\w+$
          type: string
        validated:
          type: boolean
      type: object
    LastLogin:
      additionalProperties: false
      description: |
        Defines when and what credential was used for the last login
      example:
        credentialId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        "on": 2000-01-23T04:56:07.000+00:00
      properties:
        credentialId:
          description: UUID v4
          format: uuid
          maxLength: 36
          pattern: ^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$
          type: string
        "on":
          format: date-time
          maxLength: 24
          type: string
      type: object
    Credential:
      additionalProperties: false
      description: |
        Description of a successful OpenID connect credential
      example:
        lastUsedOn: 2000-01-23T04:56:07.000+00:00
        disabledBy: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        provider: google
        identityID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        tenantID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        credentialID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        disabledOn: 2000-01-23T04:56:07.000+00:00
        createdOn: 2000-01-23T04:56:07.000+00:00
        subjectID: aSDDfasd23Dfasdf
      properties:
        credentialID:
          description: UUID v4
          format: uuid
          maxLength: 36
          pattern: ^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$
          type: string
        provider:
          description: OIDC provider that was used to handle authentication of this
            user.
          example: google
          maxLength: 255
          pattern: ^\w+$
          readOnly: true
          type: string
        subjectID:
          description: ID of the remote OIDC server gives to this identity
          example: aSDDfasd23Dfasdf
          maxLength: 255
          pattern: ^[0-9a-zA-Z_-]+$
          readOnly: true
          type: string
        identityID:
          description: UUID v4
          format: uuid
          maxLength: 36
          pattern: ^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$
          type: string
        tenantID:
          description: UUID v4
          format: uuid
          maxLength: 36
          pattern: ^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$
          type: string
        createdOn:
          format: date-time
          maxLength: 24
          type: string
        lastUsedOn:
          format: date-time
          maxLength: 24
          type: string
        disabledOn:
          format: date-time
          maxLength: 24
          nullable: true
          type: string
        disabledBy:
          description: UUID v4
          format: uuid
          maxLength: 36
          nullable: true
          pattern: ^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$
          type: string
      type: object
    OFACSearch:
      properties:
        entityId:
          description: SDN EntityID of the Entity
          example: "2141"
          type: string
        sdnName:
          description: Name of the SDN entity
          example: John Smith
          type: string
        sdnType:
          description: SDN entity type
          example: Individual
          type: string
        match:
          description: Percentage of similarity between the Customer name and this
            OFAC entity
          example: 0.91
          type: number
        createdAt:
          example: 2016-08-29T09:12:33.001Z
          format: date-time
          type: string
      type: object
    Phone:
      additionalProperties: false
      description: Phone number
      example:
        number: number
        validated: true
        identityID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        phoneID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        type: home
      properties:
        identityID:
          description: UUID v4
          format: uuid
          maxLength: 36
          pattern: ^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$
          type: string
        phoneID:
          description: UUID v4
          format: uuid
          maxLength: 36
          pattern: ^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$
          type: string
        number:
          format: phone
          maxLength: 15
          pattern: ^[0-9]+$
          type: string
        validated:
          type: boolean
        type:
          enum:
          - home
          - mobile
          - work
          type: string
      type: object
    Address:
      additionalProperties: false
      description: Address of the Identity
      example:
        country: US
        validated: true
        address2: address2
        city: Cedar Falls
        identityID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        address1: 111 Main St.
        postalCode: "50613"
        state: IA
        type: primary
        addressID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        identityID:
          description: UUID v4
          format: uuid
          maxLength: 36
          pattern: ^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$
          type: string
        addressID:
          description: UUID v4
          format: uuid
          maxLength: 36
          pattern: ^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$
          type: string
        type:
          enum:
          - primary
          - secondary
          type: string
        address1:
          example: 111 Main St.
          maxLength: 255
          pattern: ^\w+$
          type: string
        address2:
          maxLength: 255
          nullable: true
          pattern: ^\w*$
          type: string
        city:
          example: Cedar Falls
          maxLength: 255
          pattern: ^\w+$
          type: string
        state:
          example: IA
          maxLength: 2
          minLength: 2
          pattern: ^\w+$
          type: string
        postalCode:
          example: "50613"
          maxLength: 5
          minLength: 5
          pattern: ^\d+$
          type: string
        country:
          example: US
          maxLength: 2
          minLength: 2
          pattern: ^\w+$
          type: string
        validated:
          type: boolean
      type: object
    Login:
      additionalProperties: false
      description: |
        User has authenticated with an OIDC now to verify the system can find them. This verifies theirs stored credentials for a user that match the arguments
      properties:
        provider:
          description: OIDC provider that was used to handle authentication of this
            user.
          example: google
          maxLength: 255
          pattern: ^\w+$
          readOnly: true
          type: string
        subjectID:
          description: ID of the remote OIDC server gives to this identity
          example: aSDDfasd23Dfasdf
          maxLength: 255
          pattern: ^[0-9a-zA-Z_-]+$
          readOnly: true
          type: string
        tenantID:
          description: UUID v4
          format: uuid
          maxLength: 36
          pattern: ^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$
          type: string
      type: object
    LoggedIn:
      additionalProperties: false
      description: User has logged in and is being given a token to proof identity
      example:
        jwt: jwt
      properties:
        jwt:
          description: JWT token that provides authentication of identity
          maxLength: 4000
          pattern: ^[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*$
          type: string
      type: object
    Register:
      additionalProperties: false
      description: Request to register a user in the system
      example:
        lastName: Doe
        addresses:
        - country: US
          address2: address2
          city: Cedar Falls
          address1: 111 Main St.
          postalCode: "50613"
          state: IA
          type: primary
        - country: US
          address2: address2
          city: Cedar Falls
          address1: 111 Main St.
          postalCode: "50613"
          state: IA
          type: primary
        - country: US
          address2: address2
          city: Cedar Falls
          address1: 111 Main St.
          postalCode: "50613"
          state: IA
          type: primary
        - country: US
          address2: address2
          city: Cedar Falls
          address1: 111 Main St.
          postalCode: "50613"
          state: IA
          type: primary
        - country: US
          address2: address2
          city: Cedar Falls
          address1: 111 Main St.
          postalCode: "50613"
          state: IA
          type: primary
        nickName: nickName
        phones:
        - number: number
          type: home
        - number: number
          type: home
        - number: number
          type: home
        - number: number
          type: home
        - number: number
          type: home
        suffix: suffix
        birthDate: 2000-01-23T04:56:07.000+00:00
        subjectID: aSDDfasd23Dfasdf
        firstName: John
        provider: google
        inviteCode: inviteCode
        tenantID: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        middleName: Jimmy
        email: john.doe@gmail.com
      properties:
        provider:
          description: OIDC provider that was used to handle authentication of this
            user.
          example: google
          maxLength: 255
          pattern: ^\w+$
          readOnly: true
          type: string
        subjectID:
          description: ID of the remote OIDC server gives to this identity
          example: aSDDfasd23Dfasdf
          maxLength: 255
          pattern: ^[0-9a-zA-Z_-]+$
          readOnly: true
          type: string
        tenantID:
          description: UUID v4
          format: uuid
          maxLength: 36
          pattern: ^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$
          type: string
        inviteCode:
          maxLength: 60
          pattern: ^w+$
          type: string
        firstName:
          example: John
          maxLength: 255
          pattern: ^\w+$
          type: string
        middleName:
          example: Jimmy
          maxLength: 255
          pattern: ^\w+$
          type: string
        lastName:
          example: Doe
          maxLength: 255
          pattern: ^\w+$
          type: string
        nickName:
          maxLength: 255
          nullable: true
          pattern: ^\w+$
          type: string
        suffix:
          maxLength: 255
          nullable: true
          pattern: ^\w+$
          type: string
        birthDate:
          format: date-time
          maxLength: 24
          type: string
        email:
          description: Email Address
          example: john.doe@gmail.com
          format: email
          maxLength: 255
          pattern: ^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$
          type: string
        phones:
          items:
            $ref: '#/components/schemas/RegisterPhone'
          maxItems: 50
          type: array
        addresses:
          items:
            $ref: '#/components/schemas/RegisterAddress'
          maxItems: 50
          type: array
      type: object
    RegisterPhone:
      additionalProperties: false
      description: Phone number
      example:
        number: number
        type: home
      properties:
        number:
          format: phone
          maxLength: 15
          pattern: ^[0-9]+$
          type: string
        type:
          enum:
          - home
          - mobile
          - work
          type: string
      type: object
    RegisterAddress:
      additionalProperties: false
      description: Address of the Identity
      example:
        country: US
        address2: address2
        city: Cedar Falls
        address1: 111 Main St.
        postalCode: "50613"
        state: IA
        type: primary
      properties:
        type:
          enum:
          - primary
          - secondary
          type: string
        address1:
          example: 111 Main St.
          maxLength: 255
          pattern: ^\w+$
          type: string
        address2:
          maxLength: 255
          nullable: true
          pattern: ^\w*$
          type: string
        city:
          example: Cedar Falls
          maxLength: 255
          pattern: ^\w+$
          type: string
        state:
          example: IA
          maxLength: 2
          minLength: 2
          pattern: ^\w+$
          type: string
        postalCode:
          example: "50613"
          maxLength: 5
          minLength: 5
          pattern: ^\d+$
          type: string
        country:
          example: US
          maxLength: 2
          minLength: 2
          pattern: ^\w+$
          type: string
      type: object
  securitySchemes:
    GatewayAuth:
      bearerFormat: JWT
      description: JWT that comes from the gateway that validates against the gateways
        public RSA key
      scheme: bearer
      type: http
    LoginAuth:
      in: cookie
      name: moov-authn
      type: apiKey
